### ISSUE TITLE
Unable to make a move in firefox

### ISSUE THREAD

**Issue by mophdog** [tomhammers/ExpressChess#1]
Hi Tom,

I was having a look at this repos and was trying to play a game against myself using a chrome browser and a firefox browser. After starting the game in chrome, I was unable to make a move in firefox, I've attached an image of the errors dev tools are giving me.

![image](https://cloud.githubusercontent.com/assets/4234861/16173556/5cc59b10-359c-11e6-9159-444ce467355d.png)

Thanks,

Matt

**Comment by tomkerr** [comment]
Thank you for your feedback Matt. I was able to reproduce the same problem.

IE and Chrome put event objects on the global window, in Firefox the event needs to be passed as the first parameter in event listeners. Hopefully you should now be able to make a move in Firefox.
